import { StyleSheet } from "react-native";
import { cores } from "./variaveis";
const papel = "#F8F7F2", papelEscuro = "#EEF0FA", regra = "#D9DDF0";
const styles = StyleSheet.create({
  sobrepor: { flex: 1, backgroundColor: cores.preto80, justifyContent: "center", padding: 16 },
  conteudo: { width: "100%", maxWidth: 480, maxHeight: "85%", flexDirection: "row", backgroundColor: papel, borderRadius: 10, overflow: "hidden", elevation: 10 },
  capa: { width: 22, backgroundColor: cores.azul, alignItems: "center", paddingTop: 22, gap: 16 }, furo: { width: 8, height: 8, borderRadius: 4, backgroundColor: papel }, corpo: { flex: 1, minWidth: 0 },
  cabecalho: { padding: 18, borderBottomWidth: 1, borderBottomColor: regra, flexDirection: "row", justifyContent: "space-between" }, tituloArea: { flexDirection: "row", alignItems: "center", gap: 8 }, iconeTitulo: { width: 19, height: 19, tintColor: cores.vermelho }, titulo: { color: cores.preto, fontSize: 20, fontWeight: "700" }, subtitulo: { color: cores.cinzaEscuro, fontSize: 12, marginTop: 3 }, botaoFechar: { width: 28, height: 28, alignItems: "center" }, fechar: { color: cores.cinzaEscuro, fontSize: 28, lineHeight: 26 },
  abas: { paddingHorizontal: 10, paddingTop: 8, backgroundColor: papelEscuro, gap: 4 }, aba: { paddingHorizontal: 12, paddingVertical: 9, borderTopLeftRadius: 7, borderTopRightRadius: 7 }, abaAtiva: { backgroundColor: papel }, textoAba: { color: cores.cinzaEscuro, fontSize: 12, fontWeight: "600" }, textoAbaAtiva: { color: cores.azul }, lista: { backgroundColor: papel },
  notificacao: { flexDirection: "row", gap: 10, padding: 14, borderBottomWidth: 1, borderBottomColor: regra }, notificacaoNova: { backgroundColor: "#FCFCFF" }, marcaNova: { position: "absolute", left: 4, top: 11, color: cores.vermelho, fontSize: 18 }, iconeContainer: { width: 34, height: 34, borderRadius: 17, backgroundColor: "#E4E8FF", alignItems: "center", justifyContent: "center" }, iconeNotificacao: { width: 17, height: 17, tintColor: cores.azul }, textos: { flex: 1 }, linhaTitulo: { flexDirection: "row", justifyContent: "space-between", gap: 6 }, tituloNotificacao: { flex: 1, color: cores.preto, fontSize: 14, fontWeight: "700" }, descricao: { color: cores.cinzaEscuro, fontSize: 13, lineHeight: 19, marginTop: 4 }, horario: { color: cores.cinzaEscuro, fontSize: 11 }, acoes: { flexDirection: "row", gap: 14, marginTop: 8 }, acaoPrincipal: { color: cores.azul, fontSize: 12, fontWeight: "600" }, acao: { color: cores.cinzaEscuro, fontSize: 12 },
  rodape: { padding: 12, borderTopWidth: 1, borderTopColor: regra, backgroundColor: papelEscuro, alignItems: "flex-end" }, textoBotao: { color: cores.azul, fontSize: 12, fontWeight: "700" }, botaoDesabilitado: { opacity: 0.4 }, vazio: { padding: 48, alignItems: "center" }, vazioTitulo: { color: cores.preto, fontSize: 16, fontWeight: "700" }, vazioTexto: { color: cores.cinzaEscuro, fontSize: 13, marginTop: 4 },
});
export default styles;
